FROM node:18-alpine

WORKDIR /app/web

COPY package*.json .

RUN --mount=type=cache,target=/app/web/.npm \
  npm set cache /app/web/.npm && \
  npm install

COPY . .

EXPOSE 8001

CMD [ "npm", "run", "dev" ]