version: '3'
services:
  go-app:
    container_name: go-app
    build:
      context: ./snippetbox
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=root password=rootpass dbname=root sslmode=disable"
    ports:
      - "7000:7000"
    depends_on:
      go_db:
        condition: service_healthy
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  pgdata: {}
