version: '3'
services:
  go-app:
    container_name: go-app
    build:
      context: ./snippetbox
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "host=go_db user=root password=root dbname=postgres sslmode=disable"
    ports:
      - "7000:7000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
